/**
 * Occupation Types Seed Data
 * Source: Dubai visa occupation dropdown reference list
 * Total: 57 occupation types
 */

export const occupations = [
  { label: 'Services', value: 'services', sortOrder: 1 },
  { label: 'Housewife', value: 'house wife', sortOrder: 2 },
  { label: 'Child', value: 'child', sortOrder: 3 },
  { label: 'Retired', value: 'retired', sortOrder: 4 },
  { label: 'Business', value: 'business', sortOrder: 5 },
  { label: 'Student / Not Allowed to Work', value: 'STUDENT / NOT ALLOWED TO WORK', sortOrder: 6 },
  { label: 'Medical Doctors', value: 'medical doctors', sortOrder: 7 },
  { label: 'Engineer', value: 'engineer', sortOrder: 8 },
  { label: 'Architect', value: 'architect', sortOrder: 9 },
  { label: 'Sales Specialist', value: 'sales specialist', sortOrder: 10 },
  { label: 'Soldier', value: 'soldier', sortOrder: 11 },
  { label: 'Clinical Scientist', value: 'clinical scientist', sortOrder: 12 },
  { label: 'University Professor', value: 'university professor', sortOrder: 13 },
  { label: 'Teacher', value: 'teacher', sortOrder: 14 },
  { label: 'Photographer', value: 'photographer', sortOrder: 15 },
  { label: 'Pilot', value: 'pilot', sortOrder: 16 },
  { label: 'Journalist', value: 'journalist', sortOrder: 17 },
  { label: 'Flight Attendant', value: 'flight attendant', sortOrder: 18 },
  { label: 'Manager', value: 'manager', sortOrder: 19 },
  { label: 'Senior Manager', value: 'senior manager', sortOrder: 20 },
  { label: 'Vice President', value: 'vice president', sortOrder: 21 },
  { label: 'Lawyer', value: 'lawyer', sortOrder: 22 },
  { label: 'Director', value: 'director', sortOrder: 23 },
  { label: 'Executive', value: 'executive', sortOrder: 24 },
  { label: 'Associate Officer', value: 'associate officer', sortOrder: 25 },
  { label: 'Businesswoman', value: 'businesswoman', sortOrder: 26 },
  { label: 'Secretary', value: 'secretary', sortOrder: 27 },
  { label: 'Physician', value: 'physician', sortOrder: 28 },
  { label: 'None', value: 'none', sortOrder: 29 },
  { label: 'Sales Representative', value: 'sales representative', sortOrder: 30 },
  { label: 'Financial Advisor', value: 'financial advisor', sortOrder: 31 },
  { label: 'Insurance Agent', value: 'insurance agent', sortOrder: 32 },
  { label: 'Financial Consultant', value: 'financial consultant', sortOrder: 33 },
  { label: 'Branch Manager', value: 'branch manager', sortOrder: 34 },
  { label: 'Advisor', value: 'advisor', sortOrder: 35 },
  { label: 'Software Engineer', value: 'software engineer', sortOrder: 36 },
  { label: 'Nurse', value: 'nurse', sortOrder: 37 },
  { label: 'Chairman of the Board', value: 'chairman of the board', sortOrder: 38 },
  { label: 'Travel Consultant', value: 'travel consultant', sortOrder: 39 },
  { label: 'IT Operation Manager', value: 'it operation manager', sortOrder: 40 },
  { label: 'Pharmacist', value: 'pharmacist', sortOrder: 41 },
  { label: 'Specialist', value: 'specialist', sortOrder: 42 },
  { label: 'Coordinator', value: 'COORDINATIOR', sortOrder: 43 },
  { label: 'Department Head', value: 'department head', sortOrder: 44 },
  { label: 'Accountant', value: 'accountant', sortOrder: 45 },
  { label: 'HR Manager', value: 'hr manager', sortOrder: 46 },
  { label: 'Marketing Manager', value: 'marketing manager', sortOrder: 47 },
  { label: 'Operations Manager', value: 'operations manager', sortOrder: 48 },
  { label: 'Project Manager', value: 'project manager', sortOrder: 49 },
  { label: 'Consultant', value: 'consultant', sortOrder: 50 },
  { label: 'Analyst', value: 'analyst', sortOrder: 51 },
  { label: 'Designer', value: 'designer', sortOrder: 52 },
  { label: 'Developer', value: 'developer', sortOrder: 53 },
  { label: 'Data Scientist', value: 'data scientist', sortOrder: 54 },
  { label: 'Product Manager', value: 'product manager', sortOrder: 55 },
  { label: 'Quality Assurance', value: 'quality assurance', sortOrder: 56 },
  { label: 'Other', value: 'other', sortOrder: 57 }
];
